logging:
  level:
    org.apache.kafka.clients.producer: WARN
spring:
  zipkin:
      # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
    #baseUrl: http://localhost:9414
    sender:
      type: kafka
  sleuth:
    sampler:
      probability: 1
  kafa:
    bootstrapServers: localhost:9092
    clientId: test-sleuth
    producer:
      batch:
        size: 1000
sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: true